### ISSUE TITLE
Error message when trying classification tasks

### ISSUE THREAD

**Issue by Jarvx** [collab-uniba/pySenti4SD#5]
When I ran the sh classification.sh -i Sample.csv  -d scc as recommended in README, I met the problems. Can someone help me out? Many thanks in advance.

Loading DSM ...
Nov 28, 2019 2:33:55 PM di.uniba.it.tdsm.vectors.MemoryVectorReader init
INFO: Loading vector store: /home/jiawei/stackoverflow/sentiment/pySenti4SD/./java/dsm.bin
Nov 28, 2019 2:34:09 PM di.uniba.it.tdsm.vectors.MemoryVectorReader init
INFO: Total vectors/dimension: 346,197/600
Vector dimension: 600
Terminato
28-Nov-19 14:34:11 - Starting classification task
28-Nov-19 14:34:11 - Ending classification task
28-Nov-19 14:34:11 - Starting ordering prediction csv
28-Nov-19 14:34:11 - Ending ordering prediction csv
28-Nov-19 14:34:11 - Starting rewriting prediction csv
[] not found in sentiment/pySenti4SD/Sample.csv
28-Nov-19 14:34:11 - Ending rewriting prediction csv

**Comment by bateman** [comment]
It's not an actual error, in fact you should have the predictions as output.
it's just because the Sample.csv is missing the id column -- it has only the text and is not actually a CSV file.
we're going to commit a new version of the sample file with ids that will not raise the warning.
sorry for the confusion
